jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  

      - name: Configure SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'bash ~/deploy.sh'

      - name: Clean Up
        run: |
          rm -rf ~/.ssh
